MDX queries:

1. WIEK 2.1
 SELECT NON EMPTY { [Measures].[Średni czas dojazdu] } ON COLUMNS, NON EMPTY { ([Patrol].[Kategoria Wieku Kierowcy].[Kategoria Wieku Kierowcy].ALLMEMBERS ) } DIMENSION PROPERTIES MEMBER_CAPTION, MEMBER_UNIQUE_NAME ON ROWS FROM [Policja] CELL PROPERTIES VALUE, BACK_COLOR, FORE_COLOR, FORMATTED_VALUE, FORMAT_STRING, FONT_NAME, FONT_SIZE, FONT_FLAGS
4. ZMIANA 2.2 (jak zrobić zestawienie dzień / noc)
 SELECT NON EMPTY { [Measures].[Średni czas dojazdu] } ON COLUMNS, NON EMPTY { ([Czas].[Pora Dnia].[Pora Dnia].ALLMEMBERS ) } DIMENSION PROPERTIES MEMBER_CAPTION, MEMBER_UNIQUE_NAME ON ROWS FROM [Policja] CELL PROPERTIES VALUE, BACK_COLOR, FORE_COLOR, FORMATTED_VALUE, FORMAT_STRING, FONT_NAME, FONT_SIZE, FONT_FLAGS
2. PŁEĆ 2.3
 SELECT NON EMPTY { [Measures].[Średni czas dojazdu] } ON COLUMNS, NON EMPTY { ([Patrol].[Płeć Kierowcy].[Płeć Kierowcy].ALLMEMBERS ) } DIMENSION PROPERTIES MEMBER_CAPTION, MEMBER_UNIQUE_NAME ON ROWS FROM [Policja] CELL PROPERTIES VALUE, BACK_COLOR, FORE_COLOR, FORMATTED_VALUE, FORMAT_STRING, FONT_NAME, FONT_SIZE, FONT_FLAGS
5. GODZINY 2.4
 SELECT NON EMPTY { [Measures].[Średni czas dojazdu] } ON COLUMNS, NON EMPTY { ([Czas].[Godzina].[Godzina].ALLMEMBERS ) } DIMENSION PROPERTIES MEMBER_CAPTION, MEMBER_UNIQUE_NAME ON ROWS FROM [Policja] CELL PROPERTIES VALUE, BACK_COLOR, FORE_COLOR, FORMATTED_VALUE, FORMAT_STRING, FONT_NAME, FONT_SIZE, FONT_FLAGS
3. RANGA 2.5
 SELECT NON EMPTY { [Measures].[Średni czas dojazdu] } ON COLUMNS, NON EMPTY { ([Patrol].[Ranga Kierowcy].[Ranga Kierowcy].ALLMEMBERS ) } DIMENSION PROPERTIES MEMBER_CAPTION, MEMBER_UNIQUE_NAME ON ROWS FROM [Policja] CELL PROPERTIES VALUE, BACK_COLOR, FORE_COLOR, FORMATTED_VALUE, FORMAT_STRING, FONT_NAME, FONT_SIZE, FONT_FLAGS


13. KOMENDY 1.1
 SELECT NON EMPTY { [Measures].[Średni czas dojazdu] } ON COLUMNS, NON EMPTY { ([Komenda].[ID Komendy].[ID Komendy].ALLMEMBERS * [Data].[Nazwa Miesiąca].[Nazwa Miesiąca].ALLMEMBERS ) } DIMENSION PROPERTIES MEMBER_CAPTION, MEMBER_UNIQUE_NAME ON ROWS FROM [Policja] CELL PROPERTIES VALUE, BACK_COLOR, FORE_COLOR, FORMATTED_VALUE, FORMAT_STRING, FONT_NAME, FONT_SIZE, FONT_FLAGS
12. REJONY 1.2
 SELECT NON EMPTY { [Measures].[F Dojazd Do Zdarzenia Count], [Measures].[Czas Dotarcia] } ON COLUMNS, NON EMPTY { ([Komenda].[Rejon].[Rejon].ALLMEMBERS * [Data].[Nazwa Miesiąca].[Nazwa Miesiąca].ALLMEMBERS ) } DIMENSION PROPERTIES MEMBER_CAPTION, MEMBER_UNIQUE_NAME ON ROWS FROM [Policja] CELL PROPERTIES VALUE, BACK_COLOR, FORE_COLOR, FORMATTED_VALUE, FORMAT_STRING, FONT_NAME, FONT_SIZE, FONT_FLAGS
10. SUMA KM 1.3
 SELECT NON EMPTY { [Measures].[Suma długości trasy] } ON COLUMNS, NON EMPTY { ([Data].[Nazwa Miesiąca].[Nazwa Miesiąca].ALLMEMBERS ) } DIMENSION PROPERTIES MEMBER_CAPTION, MEMBER_UNIQUE_NAME ON ROWS FROM [Policja] CELL PROPERTIES VALUE, BACK_COLOR, FORE_COLOR, FORMATTED_VALUE, FORMAT_STRING, FONT_NAME, FONT_SIZE, FONT_FLAGS
11. TYP POJAZDU 1.4 (jak policzyć nielądowe razem)
 SELECT NON EMPTY { [Measures].[F Dojazd Do Zdarzenia Count] } ON COLUMNS, NON EMPTY { ([Pojazd].[Typ].[Typ].ALLMEMBERS * [Data].[Nazwa Miesiąca].[Nazwa Miesiąca].ALLMEMBERS ) } DIMENSION PROPERTIES MEMBER_CAPTION, MEMBER_UNIQUE_NAME ON ROWS FROM ( SELECT ( -{ [Pojazd].[Typ].&[Motor], [Pojazd].[Typ].&[Radiowóz] } ) ON COLUMNS FROM [Policja]) CELL PROPERTIES VALUE, BACK_COLOR, FORE_COLOR, FORMATTED_VALUE, FORMAT_STRING, FONT_NAME, FONT_SIZE, FONT_FLAGS
6. MARKI AWARIE 1.5
 SELECT NON EMPTY { [Measures].[F Awaria Count] } ON COLUMNS, NON EMPTY { ([Pojazd].[Marka].[Marka].ALLMEMBERS ) } DIMENSION PROPERTIES MEMBER_CAPTION, MEMBER_UNIQUE_NAME ON ROWS FROM [Policja] CELL PROPERTIES VALUE, BACK_COLOR, FORE_COLOR, FORMATTED_VALUE, FORMAT_STRING, FONT_NAME, FONT_SIZE, FONT_FLAGS
9. BRAK MIEJSCA ZDARZENIA 1.6 (jak zrobić zestawienie brak / inne)
 SELECT NON EMPTY { [Measures].[Średni czas dojazdu] } ON COLUMNS, NON EMPTY { ([Miejsce Zdarzenia].[Miasto].[Miasto].ALLMEMBERS ) } DIMENSION PROPERTIES MEMBER_CAPTION, MEMBER_UNIQUE_NAME ON ROWS FROM [Policja] CELL PROPERTIES VALUE, BACK_COLOR, FORE_COLOR, FORMATTED_VALUE, FORMAT_STRING, FONT_NAME, FONT_SIZE, FONT_FLAGS
7. RANGA MARKA 1.7
 SELECT NON EMPTY { [Measures].[Średni czas dojazdu] } ON COLUMNS, NON EMPTY { ([Pojazd].[Model].[Model].ALLMEMBERS * [Patrol].[Ranga Kierowcy].[Ranga Kierowcy].ALLMEMBERS ) } DIMENSION PROPERTIES MEMBER_CAPTION, MEMBER_UNIQUE_NAME ON ROWS FROM [Policja] CELL PROPERTIES VALUE, BACK_COLOR, FORE_COLOR, FORMATTED_VALUE, FORMAT_STRING, FONT_NAME, FONT_SIZE, FONT_FLAGS
8. TYP AWARII 1.8
 SELECT NON EMPTY { [Measures].[F Awaria Count] } ON COLUMNS, NON EMPTY { ([Opis Awarii].[Typ Awarii].[Typ Awarii].ALLMEMBERS ) } DIMENSION PROPERTIES MEMBER_CAPTION, MEMBER_UNIQUE_NAME ON ROWS FROM [Policja] CELL PROPERTIES VALUE, BACK_COLOR, FORE_COLOR, FORMATTED_VALUE, FORMAT_STRING, FONT_NAME, FONT_SIZE, FONT_FLAGS